### ISSUE TITLE
Java or Kotlin?

### ISSUE THREAD

**Issue by nickebbitt** [autotraderuk/chaos-kraken#6]
Unsure whether to progress this project as a Java or Kotlin codebase? My skills are mainly Java, very minimal Kotlin.

If any contributors want to get involved I'm happy to stay Kotlin and learn as we go.

**Comment by timyates** [comment]
I have similar skills, but want to improve that situation 😉

**Comment by nickebbitt** [comment]
Well, since it's just the two of us so far, let's stick with Kotlin and skill up in tandem :)
